apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: db0
    user: apiestas
    password: apiestas
    url: http://influxdb:8086
    isDefault: true
    editable: true