version: '3.4'
services:
  db:
    container_name: "mongo"
    image: mongo:4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db'
    ports:
      - "27017:27017"
    command: mongod --logpath /dev/null
  crawler:
    container_name: crawler
    build: .
    environment:
      - APIESTAS_API_URL=api:8000
    depends_on:
      - api
    command: crawler
  api:
    container_name: api
    build: .
    environment:
      - DB_CONNECTION=mongodb://db:27017
      - DEBUG=true
    ports:
      - 8000:8000
    depends_on:
      - db
    command: api
volumes:
  mongo:
    name: mongo