version: '3.2'
services:
  mongo:
    image: "mongo:4.0-xenial"
    ports:
      - "27017:27017"
  tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_CONNECTION=mongodb://db:27017
      - DEBUG=true
    depends_on:
      - mongo
    entrypoint: pytest
    volumes:
      - ..:/apiestas
    command: "-v /apiestas/api/tests/"
