version: '3.6'
services:
  mongo:
    image: "mongo:4.0-xenial"
    container_name: mongo
    volumes:
      - rs1:/data/db
    networks:
      - localnet
    ports:
      - "27017:27017"

  crawler:
    container_name: crawler
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - APIESTAS_API_URL=api:8000
    depends_on:
      - api
    command: crawler
    networks:
      - localnet

  api:
    container_name: api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_CONNECTION=mongodb://mongo:27017
      - DEBUG=true
    ports:
      - 9000:8000
    depends_on:
      - mongo
    command: api
    networks:
      - localnet

volumes:
  rs1:

networks:
  localnet:
    attachable: true
