from arbs.calculator import process_bets

test_match = {
    "bets": [
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "1xbet",
         "odds": [5.45, 1.13],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "bet-at-home",
         "odds": [4.67, 1.13],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "betago",
         "odds": [5.00, 1.14],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "bwin",
         "odds": [4.40, 1.17],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "coolbet",
         "odds": [5.24, 1.14],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "unibet",
         "odds": [4.60, 1.16],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "pinnacle",
         "odds": [5.32, 1.14],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "william-hill",
         "odds": [4.50, 1.17],
         },
        {"bet_type": "Home/Away",
         "bet_scope": "Full Time",
         "is_back": True,
         "slug": "test-bookmaker-with-wrong-odds",
         "odds": [4.50, 2.17],
         }
    ]
}

arbs = process_bets(test_match["bets"])
assert len(arbs) == 8